### ISSUE TITLE
Should accept arguments what string or character to be count

### ISSUE THREAD

**Issue by vindecodex** [vindecodex/counting-str#3]
String = > Hello, World
Arguments => l (L)

return 3; since String contains 3 l's (L)'s

**Comment by nikhil-chaurasia14** [comment]
Hello vindecodex,
what should the code return in the following condition?
String => AAAaaaaaa
Arguments => aa

**Comment by vindecodex** [comment]
> Hello vindecodex,
> what should the code return in the following condition?
> String => AAAaaaaaa
> Arguments => aa

It should return 5
AAA|aa|aaaa - 1
AAAa|aa|aaa - 2
AAAaa|aa|aa - 3
AAAaaa|aa|a - 4
AAAaaaa|aa| - 5

That's the idea maybe soon will add options with no repeat and for the example arguments it should return 3
AAA|aa|aaaa - 1
AAAaa|aa|aa - 2
AAAaaaa|aa| - 3

For now it should return 5 will add another issue for the options.
